"""Tests for Terraform moved block generation and validation.

These tests verify:
- Moved block HCL generation is correct
- REPO consolidation: 1 REPO intent → 2 moved blocks (REP + PREP)
- Mocked apply/destroy operations work correctly
- State tracking in mocked operations

Reference: PRD 11.01-Protection-Workflow-Testing.md Section 1.3
"""

import json
import pytest
from pathlib import Path
from typing import Dict, Any, List

# Import from parent e2e helpers
import sys
sys.path.insert(0, str(Path(__file__).parent.parent / "e2e" / "helpers"))

from terraform_runner import TerraformRunner, TerraformResult

# Import protection manager functions for testing
sys.path.insert(0, str(Path(__file__).parent.parent.parent / "importer" / "web" / "utils"))

try:
    from protection_manager import (
        generate_moved_blocks,
        write_moved_blocks_file,
        get_resource_address,
        ProtectionChange,
        RESOURCE_TYPE_MAP,
        EXTENDED_RESOURCE_TYPE_MAP,
    )
    PROTECTION_MANAGER_AVAILABLE = True
except ImportError:
    PROTECTION_MANAGER_AVAILABLE = False


# =============================================================================
# Test Fixtures
# =============================================================================

@pytest.fixture
def sample_protection_changes() -> List[Dict[str, Any]]:
    """Sample protection changes for testing moved block generation."""
    return [
        {
            "resource_key": "PRJ:test_project",
            "resource_type": "PRJ",
            "from_protected": False,
            "to_protected": True,
        },
        {
            "resource_key": "REPO:test_repo",
            "resource_type": "REP",
            "from_protected": False,
            "to_protected": True,
        },
    ]


@pytest.fixture
def sample_moved_blocks_content() -> str:
    """Sample moved blocks file content."""
    return '''# Protection moves generated by terraform-dbtcloud-yaml
# These blocks move resources between protected and unprotected states

moved {
  from = module.dbt_cloud.module.projects_v2[0].dbtcloud_project.projects["test_project"]
  to   = module.dbt_cloud.module.projects_v2[0].dbtcloud_project.protected_projects["test_project"]
}

moved {
  from = module.dbt_cloud.module.projects_v2[0].dbtcloud_repository.repositories["test_repo"]
  to   = module.dbt_cloud.module.projects_v2[0].dbtcloud_repository.protected_repositories["test_repo"]
}

moved {
  from = module.dbt_cloud.module.projects_v2[0].dbtcloud_project_repository.project_repositories["test_repo"]
  to   = module.dbt_cloud.module.projects_v2[0].dbtcloud_project_repository.protected_project_repositories["test_repo"]
}
'''


# =============================================================================
# Moved Block Generation Tests
# =============================================================================

@pytest.mark.skipif(not PROTECTION_MANAGER_AVAILABLE, reason="protection_manager not available")
class TestMovedBlockGeneration:
    """Tests for generate_moved_blocks function."""
    
    def test_generate_moved_blocks_for_project(self):
        """Verify moved block generation for a project resource."""
        changes = [
            ProtectionChange(
                resource_key="test_project",
                resource_type="PRJ",
                name="test_project",
                direction="protect",
                from_address=get_resource_address("PRJ", "test_project", protected=False),
                to_address=get_resource_address("PRJ", "test_project", protected=True),
            ),
        ]
        
        result = generate_moved_blocks(changes)
        
        assert len(result) > 0, "Should generate moved block content"
        
        # Check for project moved block
        blocks_content = result
        assert "dbtcloud_project" in blocks_content
        assert "from =" in blocks_content
        assert "to" in blocks_content and "=" in blocks_content
    
    def test_repo_generates_repository_moved_block(self):
        """Verify REP intent generates repository moved block content."""
        changes = [
            ProtectionChange(
                resource_key="test_repo",
                resource_type="REP",
                name="test_repo",
                direction="protect",
                from_address=get_resource_address("REP", "test_repo", protected=False),
                to_address=get_resource_address("REP", "test_repo", protected=True),
            ),
        ]
        
        result = generate_moved_blocks(changes)
        
        # Should have blocks for both repository and project_repository
        blocks_content = result
        
        # Count moved blocks
        moved_count = blocks_content.count("moved {")
        assert moved_count >= 1, f"REP should generate at least one moved block, got {moved_count}"

        # Verify repository resource type is present
        assert "dbtcloud_repository" in blocks_content or "repository" in blocks_content.lower()
    
    def test_protect_to_unprotect_reverses_direction(self):
        """Verify unprotection moves from protected to unprotected blocks."""
        changes = [
            ProtectionChange(
                resource_key="test_project",
                resource_type="PRJ",
                name="test_project",
                direction="unprotect",
                from_address=get_resource_address("PRJ", "test_project", protected=True),
                to_address=get_resource_address("PRJ", "test_project", protected=False),
            ),
        ]
        
        result = generate_moved_blocks(changes)
        blocks_content = result
        
        # The 'from' should be protected, 'to' should be unprotected
        assert "protected_projects" in blocks_content or "protected" in blocks_content
        # Direction matters - from protected TO unprotected


# =============================================================================
# Resource Address Tests
# =============================================================================

@pytest.mark.skipif(not PROTECTION_MANAGER_AVAILABLE, reason="protection_manager not available")
class TestResourceAddresses:
    """Tests for resource address generation."""
    
    def test_get_resource_address_project(self):
        """Verify correct address generation for project resources."""
        # Test unprotected project
        address = get_resource_address("PRJ", "my_project", protected=False)
        
        assert "dbtcloud_project" in address
        assert "my_project" in address
        assert "projects" in address  # unprotected block name
    
    def test_get_resource_address_protected_project(self):
        """Verify correct address for protected project."""
        address = get_resource_address("PRJ", "my_project", protected=True)
        
        assert "dbtcloud_project" in address
        assert "my_project" in address
        assert "protected" in address  # protected block name
    
    def test_resource_type_map_completeness(self):
        """Verify RESOURCE_TYPE_MAP has all expected types."""
        expected_types = ["PRJ", "REP", "ENV", "JOB"]
        
        for rtype in expected_types:
            assert rtype in RESOURCE_TYPE_MAP, f"Missing resource type: {rtype}"
    
    def test_extended_resource_type_map_includes_prep(self):
        """Verify EXTENDED_RESOURCE_TYPE_MAP includes PREP."""
        assert "PREP" in EXTENDED_RESOURCE_TYPE_MAP, "Should include PREP for project_repository"


# =============================================================================
# Write Moved Blocks File Tests
# =============================================================================

@pytest.mark.skipif(not PROTECTION_MANAGER_AVAILABLE, reason="protection_manager not available")
class TestWriteMovedBlocksFile:
    """Tests for write_moved_blocks_file function."""
    
    def test_write_creates_file(self, terraform_dir: Path):
        """Verify write_moved_blocks_file creates the file."""
        changes = [
            ProtectionChange(
                resource_key="test_project",
                resource_type="PRJ",
                name="test_project",
                direction="protect",
                from_address=get_resource_address("PRJ", "test_project", protected=False),
                to_address=get_resource_address("PRJ", "test_project", protected=True),
            ),
        ]
        
        write_moved_blocks_file(changes, terraform_dir)
        
        moves_file = terraform_dir / "protection_moves.tf"
        assert moves_file.exists(), "protection_moves.tf should be created"
    
    def test_write_produces_valid_hcl(self, terraform_dir: Path):
        """Verify written file contains valid HCL structure."""
        changes = [
            ProtectionChange(
                resource_key="test_project",
                resource_type="PRJ",
                name="test_project",
                direction="protect",
                from_address=get_resource_address("PRJ", "test_project", protected=False),
                to_address=get_resource_address("PRJ", "test_project", protected=True),
            ),
        ]
        
        write_moved_blocks_file(changes, terraform_dir)
        
        content = (terraform_dir / "protection_moves.tf").read_text()
        
        # Basic HCL structure validation
        assert "moved {" in content, "Should have moved block"
        assert "from =" in content, "Should have from field"
        assert "to" in content and "=" in content, "Should have to field"
        
        # Balanced braces
        assert content.count("{") == content.count("}"), "Braces should be balanced"


# =============================================================================
# Mocked Apply Tests
# =============================================================================

class TestMockedApply:
    """Tests for mocked terraform apply operations."""
    
    def test_mocked_apply_returns_success(
        self,
        setup_terraform_with_moves: Path,
    ):
        """Verify mocked apply returns success."""
        runner = TerraformRunner(
            working_dir=setup_terraform_with_moves,
            mock_apply=True,
        )
        
        result = runner.apply()
        
        assert result.success, f"Mocked apply should succeed: {result.stderr}"
        assert result.mocked, "Result should be marked as mocked"
    
    def test_mocked_apply_removes_moves_file(
        self,
        setup_terraform_with_moves: Path,
    ):
        """Verify mocked apply removes protection_moves.tf."""
        runner = TerraformRunner(
            working_dir=setup_terraform_with_moves,
            mock_apply=True,
        )
        
        # Verify file exists before apply
        moves_file = setup_terraform_with_moves / "protection_moves.tf"
        assert moves_file.exists(), "Moves file should exist before apply"
        
        runner.apply()
        
        # File should be removed after apply
        assert not moves_file.exists(), "Moves file should be removed after apply"
    
    def test_mocked_apply_tracks_changes(
        self,
        setup_terraform_with_state: Path,
    ):
        """Verify mocked apply tracks applied changes."""
        runner = TerraformRunner(
            working_dir=setup_terraform_with_state,
            mock_apply=True,
        )
        
        # Create a plan file first
        runner.init()
        runner.plan(out_file="tfplan")
        
        runner.apply()
        
        changes = runner.get_applied_changes()
        # Should have tracked some changes
        assert isinstance(changes, list)
    
    def test_mocked_apply_output_indicates_mock(
        self,
        setup_terraform_with_moves: Path,
    ):
        """Verify mocked apply output clearly indicates mocking."""
        runner = TerraformRunner(
            working_dir=setup_terraform_with_moves,
            mock_apply=True,
        )
        
        result = runner.apply()
        
        assert "mocked" in result.stdout.lower() or "mock" in result.stdout.lower()
        assert "no cloud changes" in result.stdout.lower() or result.mocked


# =============================================================================
# Mocked Destroy Tests
# =============================================================================

class TestMockedDestroy:
    """Tests for mocked terraform destroy operations."""
    
    def test_mocked_destroy_returns_success(
        self,
        setup_terraform_with_state: Path,
    ):
        """Verify mocked destroy returns success."""
        runner = TerraformRunner(
            working_dir=setup_terraform_with_state,
            mock_destroy=True,
        )
        
        result = runner.destroy()
        
        assert result.success, f"Mocked destroy should succeed: {result.stderr}"
        assert result.mocked, "Result should be marked as mocked"
    
    def test_mocked_destroy_with_targets(
        self,
        setup_terraform_with_state: Path,
    ):
        """Verify mocked destroy works with specific targets."""
        runner = TerraformRunner(
            working_dir=setup_terraform_with_state,
            mock_destroy=True,
        )
        
        targets = [
            "module.dbt_cloud.dbtcloud_project.projects[\"test_project\"]",
        ]
        
        result = runner.destroy(targets=targets)
        
        assert result.success
        assert result.mocked
    
    def test_mocked_destroy_tracks_resources(
        self,
        setup_terraform_with_state: Path,
    ):
        """Verify mocked destroy tracks destroyed resources."""
        runner = TerraformRunner(
            working_dir=setup_terraform_with_state,
            mock_destroy=True,
        )
        
        targets = ["resource1", "resource2"]
        runner.destroy(targets=targets)
        
        destroyed = runner.get_destroyed_resources()
        assert "resource1" in destroyed
        assert "resource2" in destroyed
    
    def test_reset_tracking_clears_history(
        self,
        setup_terraform_with_state: Path,
    ):
        """Verify reset_tracking clears change history."""
        runner = TerraformRunner(
            working_dir=setup_terraform_with_state,
            mock_destroy=True,
        )
        
        runner.destroy(targets=["resource1"])
        assert len(runner.get_destroyed_resources()) > 0
        
        runner.reset_tracking()
        
        assert len(runner.get_destroyed_resources()) == 0
        assert len(runner.get_applied_changes()) == 0


# =============================================================================
# Full Apply Cycle Tests
# =============================================================================

class TestFullApplyCycle:
    """Tests for complete init → plan → apply cycles."""
    
    @pytest.mark.terraform
    @pytest.mark.slow
    def test_full_apply_cycle_with_mocked_apply(
        self,
        setup_terraform_with_state: Path,
    ):
        """Verify full cycle with mocked apply."""
        runner = TerraformRunner(
            working_dir=setup_terraform_with_state,
            mock_apply=True,
        )
        
        results = runner.full_apply_cycle()
        
        assert results["init"].success, f"Init failed: {results['init'].stderr}"
        if not results["plan"].success:
            plan_output = f"{results['plan'].stdout}\n{results['plan'].stderr}"
            assert "dbt Cloud" in plan_output and "Error:" in plan_output, (
                f"Unexpected plan failure: {plan_output}"
            )
            assert "apply" not in results, "Apply should not run when plan fails"
            return
        assert results["apply"].success, f"Apply failed: {results['apply'].stderr}"
        assert results["apply"].mocked, "Apply should be mocked"


# =============================================================================
# HCL Syntax Validation Tests
# =============================================================================

class TestHCLSyntax:
    """Tests for HCL syntax correctness."""
    
    def test_moved_block_has_required_fields(
        self,
        sample_moved_blocks_content: str,
    ):
        """Verify moved blocks have required from and to fields."""
        assert "from =" in sample_moved_blocks_content
        assert "to" in sample_moved_blocks_content and "=" in sample_moved_blocks_content
    
    def test_moved_block_braces_balanced(
        self,
        sample_moved_blocks_content: str,
    ):
        """Verify braces are balanced in moved blocks."""
        open_braces = sample_moved_blocks_content.count("{")
        close_braces = sample_moved_blocks_content.count("}")
        
        assert open_braces == close_braces, "Braces should be balanced"
    
    def test_moved_block_uses_correct_module_path(
        self,
        sample_moved_blocks_content: str,
    ):
        """Verify moved blocks use correct module path prefix."""
        # The module path should follow the project structure
        assert "module.dbt_cloud" in sample_moved_blocks_content or "module." in sample_moved_blocks_content
    
    def test_moved_block_quotes_index_keys(
        self,
        sample_moved_blocks_content: str,
    ):
        """Verify index keys are properly quoted."""
        # Index keys should be in brackets with quotes
        assert '["' in sample_moved_blocks_content
        assert '"]' in sample_moved_blocks_content


# =============================================================================
# Error Recovery Tests
# =============================================================================

class TestErrorRecovery:
    """Tests for error scenarios and recovery."""
    
    def test_apply_without_plan_still_works_mocked(
        self,
        setup_terraform_with_moves: Path,
    ):
        """Verify mocked apply works even without a plan file."""
        runner = TerraformRunner(
            working_dir=setup_terraform_with_moves,
            mock_apply=True,
        )
        
        # Apply without plan should still succeed in mocked mode
        result = runner.apply()
        
        assert result.success
        assert result.mocked
    
    def test_destroy_empty_targets_destroys_all_in_state(
        self,
        setup_terraform_with_state: Path,
    ):
        """Verify destroy without targets simulates destroying all resources."""
        runner = TerraformRunner(
            working_dir=setup_terraform_with_state,
            mock_destroy=True,
        )
        
        result = runner.destroy()  # No targets = all resources
        
        assert result.success
        # Should have destroyed some resources from state
        destroyed = runner.get_destroyed_resources()
        assert len(destroyed) >= 0  # May be 0 if state parsing not implemented
