# Protection moves - valid configuration for testing
# Generated by protection workflow
# Reference: PRD 11.01-Protection-Workflow-Testing.md Section 1.3

# Move project from unprotected to protected block
moved {
  from = module.dbt_cloud.module.projects_v2[0].dbtcloud_project.projects["test_project"]
  to   = module.dbt_cloud.module.projects_v2[0].dbtcloud_project.protected_projects["test_project"]
}

# Move repository from unprotected to protected block
moved {
  from = module.dbt_cloud.module.projects_v2[0].dbtcloud_repository.repositories["test_project"]
  to   = module.dbt_cloud.module.projects_v2[0].dbtcloud_repository.protected_repositories["test_project"]
}

# Move project_repository link from unprotected to protected block
moved {
  from = module.dbt_cloud.module.projects_v2[0].dbtcloud_project_repository.project_repositories["test_project"]
  to   = module.dbt_cloud.module.projects_v2[0].dbtcloud_project_repository.protected_project_repositories["test_project"]
}
