"""YAML to Terraform deployment setup.

This module creates a Terraform deployment directory that uses the 
terraform-dbtcloud-yaml module to deploy dbt Cloud resources from 
a normalized YAML configuration file.

Follows the same pattern as test/e2e_test/ - generates main.tf that
references the root module, and relies on TF_VAR_* environment 
variables for credentials (not stored in files).
"""

import shutil
from pathlib import Path
from typing import Optional


class YamlToTerraformConverter:
    """Sets up a Terraform deployment directory for deploying dbt Cloud resources."""

    def __init__(
        self,
        module_source: Optional[str] = None,
        provider_version: str = "= 1.5.1",
    ):
        """Initialize the converter.

        Args:
            module_source: Source path for the terraform-dbtcloud-yaml module.
                          If None, calculates relative path from output directory.
            provider_version: dbtcloud provider version constraint.
        """
        self.module_source = module_source
        self.provider_version = provider_version
        # Get the repo root (parent of importer directory)
        self._repo_root = Path(__file__).parent.parent.resolve()

    def convert(
        self,
        yaml_file: str,
        output_dir: str,
        target_host_url: Optional[str] = None,
        target_account_id: Optional[int] = None,
        target_token: Optional[str] = None,
    ) -> None:
        """Create a Terraform deployment directory.

        Args:
            yaml_file: Path to the normalized YAML configuration file.
            output_dir: Directory to create the Terraform files in.
            target_host_url: Target dbt Cloud host URL (for reference only, uses env vars).
            target_account_id: Target dbt Cloud account ID (for reference only, uses env vars).
            target_token: Target dbt Cloud API token (not stored - uses env vars).
        """
        yaml_path = Path(yaml_file).resolve()
        output_path = Path(output_dir).resolve()
        output_path.mkdir(parents=True, exist_ok=True)

        # Copy YAML file to output directory
        yaml_dest = output_path / "dbt-cloud-config.yml"
        shutil.copy2(yaml_path, yaml_dest)

        # Calculate relative path from output dir to repo root
        # This follows the same pattern as test/e2e_test which uses "../.."
        if self.module_source:
            module_source = self.module_source
        else:
            try:
                # Calculate relative path
                module_source = str(Path("..") / output_path.relative_to(self._repo_root).parent)
                # Simplify: if output is terraform_output, relative is ".."
                # Count how many levels deep we are from repo root
                rel_parts = output_path.relative_to(self._repo_root).parts
                module_source = "/".join([".."] * len(rel_parts))
            except ValueError:
                # Output dir is outside repo, use absolute path
                module_source = str(self._repo_root)

        # Generate main.tf (following test/e2e_test/main.tf pattern)
        self._write_main_tf(output_path, module_source)

    def _write_main_tf(self, output_path: Path, module_source: str) -> None:
        """Write the main.tf file following the e2e test pattern."""
        content = f'''# Deployment Configuration
# Generated by dbt Magellan
#
# Credentials are provided via environment variables:
#   TF_VAR_dbt_account_id - Target account ID
#   TF_VAR_dbt_token      - API token (service token or PAT)
#   TF_VAR_dbt_host_url   - Host URL (e.g., https://cloud.getdbt.com)
#   TF_VAR_dbt_pat        - Optional: PAT for GitHub App integration

terraform {{
  required_version = ">= 1.5"
  required_providers {{
    dbtcloud = {{
      source  = "dbt-labs/dbtcloud"
      version = "{self.provider_version}"
    }}
  }}
}}

provider "dbtcloud" {{
  account_id = var.dbt_account_id
  token      = var.dbt_token
  host_url   = var.dbt_host_url
}}

variable "dbt_account_id" {{
  description = "dbt Cloud account ID"
  type        = number
}}

variable "dbt_token" {{
  description = "dbt Cloud API token"
  type        = string
  sensitive   = true
}}

variable "dbt_host_url" {{
  description = "dbt Cloud API URL (including /api suffix)"
  type        = string
  default     = "https://cloud.getdbt.com/api"
}}

variable "dbt_pat" {{
  description = "dbt Cloud Personal Access Token (dbtu_*) for GitHub App integration"
  type        = string
  sensitive   = true
  default     = null
}}

module "dbt_cloud" {{
  source = "{module_source}"

  # Pass credentials to the module
  dbt_account_id = var.dbt_account_id
  dbt_token      = var.dbt_token
  dbt_host_url   = var.dbt_host_url
  dbt_pat        = var.dbt_pat

  yaml_file   = "${{path.module}}/dbt-cloud-config.yml"
  target_name = "deployment"

  # Credential token mapping (add secrets here if needed)
  token_map = {{
    # Example: "databricks_token" = var.databricks_token
  }}
}}

# Outputs for verification
output "project_ids" {{
  description = "Map of project keys to IDs"
  value       = module.dbt_cloud.v2_project_ids
}}

output "environment_ids" {{
  description = "Map of environment keys to IDs"
  value       = module.dbt_cloud.v2_environment_ids
}}

output "job_ids" {{
  description = "Map of job keys to IDs"
  value       = module.dbt_cloud.v2_job_ids
}}

output "connection_ids" {{
  description = "Map of connection keys to IDs"
  value       = module.dbt_cloud.v2_connection_ids
}}

output "repository_ids" {{
  description = "Map of repository keys to IDs"
  value       = module.dbt_cloud.v2_repository_ids
}}
'''
        (output_path / "main.tf").write_text(content)
